name: IoTFS

on:
  push:
    branches:
      - dev
      - test_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.5
        uses: actions/setup-python@master
        with:
          python-version: 3.5
      - name: Upgrading pip
        run: python -m pip install --upgrade pip
      - name: Installing fuse # Create new action for this -> with statement
        run: |
          sudo apt-get install ninja-build
          wget https://github.com/libfuse/libfuse/releases/download/fuse-3.6.2/fuse-3.6.2.tar.xz
          pip install meson
          tar xf fuse-3.6.2.tar.xz
          cd fuse-3.6.2; mkdir build; cd build; meson ..; ninja; sudo ninja install
          ls /usr/local/lib
          ls /lib
          sudo ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.6.2 /lib/x86_64-linux-gnu/libfuse3.so.3
      - name: Checkout IoTFS
        uses: actions/checkout@master
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./src --max-line-length 120
      - name: Start application
        run: |
          mkdir dir
          python3 ./src/main.py ../dir --debug-fuse --debug
      - name: Application status
        run: |
          ls
          cat pyfuse3.log
          cat TestFs.log
          cat MQTT.log
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
