name: IoTFS

on:
  push:
    branches:
      - dev
      - test_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Upgrading pip
        run: python -m pip install --upgrade pip
      - name: Installing fuse 3.7 # Create new action for this -> with statement
        env: 
          FUSE_VERSION: 3.7.0
        run: |
          sudo apt-get install ninja-build
          wget https://github.com/libfuse/libfuse/releases/download/fuse-$FUSE_VERSION/fuse-$FUSE_VERSION.tar.xz
          pip install meson
          tar xf fuse-$FUSE_VERSION.tar.xz
          cd fuse-$FUSE_VERSION; mkdir build; cd build; meson ..; ninja; sudo ninja install
          ls /usr/local/lib
          ls /lib
          sudo ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.$FUSE_VERSION /lib/x86_64-linux-gnu/libfuse3.so.3
      - name: Install MQTT Broker
        run: |
          sudo apt-get install mosquitto
          echo `service mosquitto status`
      - name: Checkout IoTFS
        uses: actions/checkout@master
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Directories # Only for testing purpose
        run: cd ..; ls;
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./src --max-line-length 120
      - name: Start Application
        run: |
          nohup python3 -u ./src/main.py dir --debug-fuse --debug &
          echo $! > app.pid
      - name: Application Status Before Test
        run: |
          cat logs/*.log
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Read Logs
        run: |
          cat logs/*.log
      - name: Stop Application
        run: |
          kill `cat app.pid` # kill resulting PID
          sudo umount dir
