name: CoreFS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - dev
      - test_actions
env:
  PACKAGE_NAME: core_fs_th_os
  PACKAGE_VERSION: 0.0.1
  PYTHON_VERSION: 3.7.4
  FUSE_VERSION: 3.7.0
jobs:
  lint: # install, lint, test, build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7.4 # env variable not working here
        uses: actions/setup-python@master
        with:
          python-version: 3.7.0
      - name: Upgrading pip
        run: python3 -m pip install --upgrade pip
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7.4]
    steps:
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Set up Python 3.7.4
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --upgrade setuptools wheel
      - name: Build Package
        run: |
          python3 setup.py sdist bdist_wheel
      - name: Upload Archive
        uses: actions/upload-artifact@master
        with:
          name: package
          path: dist # needs dynamic name
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [$PYTHON_VERSION]
    env:
      PYTHONPATH: corefs
    steps:
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Set up Python 3.7.4
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrading pip
        run: python3 -m pip install --upgrade pip
      - name: Installing FUSE
        run: |
          sudo chmod 777 install_fuse.sh
          ./install_fuse.sh $FUSE_VERSION
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Lookup
        run: |
          echo "$PYTHONPATH"
      - name: Start Application
        run: |
          nohup python3 -u ./corefs/core.py dir --debug &
          echo $! > app.pid
      - name: Application Status Before Test
        run: |
          cat logs/*.log
      - name: Run Basic Tests with pytest
        run: |
          pip3 install pytest
          pytest --ignore tests/advanced
      - name: Read Logs
        run: |
          cat logs/*.log
      - name: Stop Application
        run: |
          kill `cat app.pid` # kill resulting PID
          sudo umount dir
  test_app:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Set up Python 3.7.4
        uses: actions/setup-python@master
        with:
          python-version: 3.7.4
      - name: Installing FUSE
        run: |
          sudo chmod 777 install_fuse.sh
          ./install_fuse.sh $FUSE_VERSION
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Download Archive
        uses: actions/download-artifact@master
        with:
          name: package
          path: dist
      - name: Lookup Archive
        run: ls
      - name: Install Package
        run: |
          pip3 install ./dist/*.tar.gz
      - name: Start Application
        run: |
          nohup python3 -u ./example_app/app.py dir --debug &
          echo $! > app.pid
      - name: Application Status Before Test
        run: |
          cat logs/*.log
      - name: Run Tests with pytest
        run: |
          pip3 install pytest
          pytest --ignore tests/advanced
          cat logs/*.log
      - name: Read Logs
        run: |
          cat logs/*.log
      - name: Stop Application
        run: |
          kill `cat app.pid` # kill resulting PID
          sudo umount dir
  test_input: # TODO: Install fuse, mqtt, python, pip; Start application; Run advanced tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Set up Python 3.7.4
        uses: actions/setup-python@master
        with:
          python-version: 3.7.4
      - name: Installing FUSE
        run: |
          sudo chmod 777 install_fuse.sh
          ./install_fuse.sh $FUSE_VERSION
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Install MQTT Broker
        run: |
          sudo apt-get install mosquitto
          echo `service mosquitto status`
      - name: Download Archive
        uses: actions/download-artifact@master
        with:
          name: package
          path: dist
      - name: Lookup Archive
        run: ls
      - name: Install Package
        run: |
          pip3 install ./dist/*.tar.gz
      - name: Start Application
        run: |
          nohup python3 -u ./example_input/app.py dir --debug &
          echo $! > app.pid
      - name: Application Status Before Test
        run: |
          cat logs/*.log
      - name: Run Tests with pytest
        run: |
          pip3 install pytest
          pytest tests/advanced/input
      - name: Read Logs
        run: |
          cat logs/*.log
      - name: Stop Application
        run: |
          kill `cat app.pid` # kill resulting PID
          sudo umount dir
  test_output:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CoreFS
        uses: actions/checkout@master
      - name: Set up Python 3.7.4
        uses: actions/setup-python@master
        with:
          python-version: 3.7.4
      - name: Installing FUSE
        run: |
          sudo chmod 777 install_fuse.sh
          ./install_fuse.sh $FUSE_VERSION
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Download Archive
        uses: actions/download-artifact@master
        with:
          name: package
          path: dist
      - name: Lookup Archive
        run: ls
      - name: Install Package
        run: |
          pip3 install ./dist/*.tar.gz
      - name: Start Application
        run: |
          nohup python3 -u ./example_output/app.py dir --debug &
          echo $! > app.pid
      - name: Application Status Before Test
        run: |
          cat logs/*.log
      - name: Run Basic Tests with pytest
        run: |
          pip3 install pytest
          pytest tests/advanced/output
      - name: Read Logs
        run: |
          cat logs/*.log
      - name: Stop Application
        run: |
          kill `cat app.pid` # kill resulting PID
          sudo umount dir
