name: Output-Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - dev
      - test_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Upgrading pip
        run: python -m pip install --upgrade pip
      - name: Installing fuse 3.7 # Create new action for this -> with statement
        env: 
          FUSE_VERSION: 3.7.0
        run: |
          sudo apt-get install ninja-build
          wget https://github.com/libfuse/libfuse/releases/download/fuse-$FUSE_VERSION/fuse-$FUSE_VERSION.tar.xz
          pip install meson
          tar xf fuse-$FUSE_VERSION.tar.xz
          cd fuse-$FUSE_VERSION; mkdir build; cd build; meson ..; ninja; sudo ninja install
          ls /usr/local/lib
          ls /lib
          sudo ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.$FUSE_VERSION /lib/x86_64-linux-gnu/libfuse3.so.3
      - name: Install MQTT Broker
        run: |
          sudo apt-get install mosquitto
          echo `service mosquitto status`